### 用户组创建
GET http://192.168.11.50:8080/workflow/rs/custom?mobile=18256968438
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjQ3LCJ1c2VyX25hbWUiOiJsaW1lbmdzaWh1YW5nIiwic2NvcGUiOlsic2VydmVyIl0sIm5pY2tuYW1lIjoi5p2O5qKm5oCd55qHIiwiZXhwIjoxNTk3OTU4OTg3LCJqdGkiOiJhMGEyZWYxZi1jNzBmLTRiODItYWRiMS1jZGQwNTdhYzBlODIiLCJjbGllbnRfaWQiOiJjbGllbnRfMiJ9.9HaTsmFiv241QwNQsHT3izVhTTDvH1FNGAyEV2NM0dI


###
GET http://192.168.11.50:8080/workflow/rs/custom?mobile=18256968438
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjQ3LCJ1c2VyX25hbWUiOiJsaW1lbmdzaWh1YW5nIiwic2NvcGUiOlsic2VydmVyIl0sIm5pY2tuYW1lIjoi5p2O5qKm5oCd55qHIiwiZXhwIjoxNTk3OTU4OTg3LCJqdGkiOiJhMGEyZWYxZi1jNzBmLTRiODItYWRiMS1jZGQwNTdhYzBlODIiLCJjbGllbnRfaWQiOiJjbGllbnRfMiJ9.9HaTsmFiv241QwNQsHT3izVhTTDvH1FNGAyEV2NM0dI


###

# curl -X POST "http://192.168.11.50:8109/special-after-sale/cc-apply-list" -H  "Request-Origion:SwaggerBootstrapUi" -H  "accept:*/*" -H  "Authorization:" -H  "Content-Type:application/json" -d "{\"keyWord\":\"\",\"page\":0,\"size\":5,\"status\":0}"
POST http://192.168.11.50:8080/workflow/special-after-sale/cc-apply-list
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMjQ3LCJ1c2VyX25hbWUiOiJsaW1lbmdzaWh1YW5nIiwic2NvcGUiOlsic2VydmVyIl0sIm5pY2tuYW1lIjoi5p2O5qKm5oCd55qHIiwiZXhwIjoxNTk3OTU4OTg3LCJqdGkiOiJhMGEyZWYxZi1jNzBmLTRiODItYWRiMS1jZGQwNTdhYzBlODIiLCJjbGllbnRfaWQiOiJjbGllbnRfMiJ9.9HaTsmFiv241QwNQsHT3izVhTTDvH1FNGAyEV2NM0dI
accept: */*
Authorization:
Content-Type: application/json

{
  "keyWord": "",
  "page": 0,
  "size": 5,
  "status": 0
}

###


###
# curl -X GET "http://localhost:8097/special-after-sale/apply-excel?deptId=&deptName=&endTime=&startTime=&status=&userId=&userName=" -H  "Request-Origion:SwaggerBootstrapUi" -H  "accept:*/*" -H  "Authorization:"
GET http://localhost:8097/special-after-sale/apply-excel?deptId=&deptName=&endTime=&startTime=&status=&userId=&userName=
Request-Origion: SwaggerBootstrapUi
accept: */*
Authorization:

###



